"""Paquete de prompts KAG (prompt-as-code, filosofía 0004).

Centraliza las task keys, los fallbacks de system prompts, las specs
(KAG_TEMPLATES) y el runtime de resolución. Los pipelines (src/kag_ingest.py,
src/kag_query.py) importan desde aquí a nivel de módulo; el seed
(src/db/seed_kag_prompts.py) importa KAG_TEMPLATES desde specs.
"""

from __future__ import annotations

from src.kag.prompts.runtime import (
    _get_prompt_pair,
    _get_system_prompt,
    get_user_template,
)

from src.kag.prompts.fallbacks import (
    ANSWER_SYSTEM_SHORT,
    AUDIT_FUSED_SYSTEM_SHORT,
    AUDITED_ANSWER_SYSTEM_SHORT,
    CHAPTER_PROPOSITIONS_SYSTEM_SHORT,
    COMBINED_SYSTEM_SHORT,
    CONTRADICTION_SYSTEM_SHORT,
    CRITIC_SYSTEM_SHORT,
    DOCUMENT_ANALYSIS_SYSTEM_SHORT,
    DOCUMENT_EXTRACT_SYSTEM_SHORT,
    DOCUMENT_SEPARATION_SYSTEM_SHORT,
    EXTRACT_SYSTEM_SHORT,
    GROUNDED_ENTITIES_SYSTEM_SHORT,
    PARAPHRASE_SYSTEM_SHORT,
    PROPOSITIONAL_SYSTEM_SHORT,
    QUERY_METADATA_SYSTEM_SHORT,
    QUERY_STRATEGY_SYSTEM_SHORT,
    QUERY_SUBQUERIES_SYSTEM_SHORT,
    QWEN_SUMMARY_SYSTEM,
    SUFFICIENCY_SYSTEM_SHORT,
    SYNTHESIS_SYSTEM_SHORT,
)
from src.kag.prompts.specs import KAG_TEMPLATES, USER_TEMPLATES
from src.kag.prompts.tasks import (
    ALL_TASK_KEYS,
    TASK_ANSWER,
    TASK_AUDIT_FUSED,
    TASK_CHAPTER_PROPOSITIONS,
    TASK_CHUNK_PARAPHRASE,
    TASK_CONTRADICTIONS,
    TASK_CRITIC_LINKING,
    TASK_CRITIC_REGEX,
    TASK_DOCUMENT_ANALYSIS,
    TASK_DOCUMENT_EXTRACT,
    TASK_DOCUMENT_SEPARATION,
    TASK_EXTRACT_ENTITIES,
    TASK_GROUNDED_ENTITIES,
    TASK_PROPOSITION_CHUNKING,
    TASK_QUERY_ANSWER,
    TASK_QUERY_METADATA,
    TASK_QUERY_STRATEGY,
    TASK_QUERY_SUBQUERIES,
    TASK_QWEN_SUMMARY,
    TASK_SUFFICIENCY,
    TASK_SYNTHESIS,
)

__all__ = [
    # task keys
    "ALL_TASK_KEYS",
    "TASK_ANSWER",
    "TASK_AUDIT_FUSED",
    "TASK_CHAPTER_PROPOSITIONS",
    "TASK_CHUNK_PARAPHRASE",
    "TASK_CONTRADICTIONS",
    "TASK_CRITIC_LINKING",
    "TASK_CRITIC_REGEX",
    "TASK_DOCUMENT_ANALYSIS",
    "TASK_DOCUMENT_EXTRACT",
    "TASK_DOCUMENT_SEPARATION",
    "TASK_EXTRACT_ENTITIES",
    "TASK_GROUNDED_ENTITIES",
    "TASK_PROPOSITION_CHUNKING",
    "TASK_QWEN_SUMMARY",
    "TASK_QUERY_ANSWER",
    "TASK_QUERY_METADATA",
    "TASK_QUERY_STRATEGY",
    "TASK_QUERY_SUBQUERIES",
    "TASK_SUFFICIENCY",
    "TASK_SYNTHESIS",
    # fallbacks de system prompts
    "ANSWER_SYSTEM_SHORT",
    "AUDIT_FUSED_SYSTEM_SHORT",
    "AUDITED_ANSWER_SYSTEM_SHORT",
    "CHAPTER_PROPOSITIONS_SYSTEM_SHORT",
    "COMBINED_SYSTEM_SHORT",
    "CONTRADICTION_SYSTEM_SHORT",
    "CRITIC_SYSTEM_SHORT",
    "DOCUMENT_ANALYSIS_SYSTEM_SHORT",
    "DOCUMENT_EXTRACT_SYSTEM_SHORT",
    "DOCUMENT_SEPARATION_SYSTEM_SHORT",
    "EXTRACT_SYSTEM_SHORT",
    "GROUNDED_ENTITIES_SYSTEM_SHORT",
    "PARAPHRASE_SYSTEM_SHORT",
    "PROPOSITIONAL_SYSTEM_SHORT",
    "QUERY_METADATA_SYSTEM_SHORT",
    "QUERY_STRATEGY_SYSTEM_SHORT",
    "QUERY_SUBQUERIES_SYSTEM_SHORT",
    "QWEN_SUMMARY_SYSTEM",
    "SUFFICIENCY_SYSTEM_SHORT",
    "SYNTHESIS_SYSTEM_SHORT",
    # specs y runtime
    "KAG_TEMPLATES",
    "USER_TEMPLATES",
    "get_user_template",
    "_get_system_prompt",
    "_get_prompt_pair",
]
